---
name: Validate YAML config.yaml
run-name: Validate YAML

on:
  workflow_call:

jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate YAML
        uses: GrantBirki/json-yaml-validate@v3
        with:
          mode: fail
          files: config.yaml
...
